// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(MyDataContext))]
    [Migration("20260902233642_PeriodCouse")]
    partial class PeriodCouse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AcademicMonth", b =>
                {
                    b.Property<int>("IdMesAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesAcademico"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdMes")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodoAcademico")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdMesAcademico");

                    b.HasIndex("IdMes");

                    b.HasIndex("IdPeriodoAcademico");

                    b.ToTable("AcademicMonths");
                });

            modelBuilder.Entity("Domain.Entities.AcademicSubPeriod", b =>
                {
                    b.Property<int>("IdPeriodoAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodoAcademico"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int");

                    b.Property<int>("IdSubPeriodo")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdPeriodoAcademico");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdSubPeriodo");

                    b.ToTable("AcademicSubPeriods");
                });

            modelBuilder.Entity("Domain.Entities.CDUser", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Classroom", b =>
                {
                    b.Property<int>("IdAula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAula"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAula");

                    b.ToTable("Classroom");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Domain.Entities.CoursePeriod", b =>
                {
                    b.Property<int>("IdCursoPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCursoPeriodo"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdCursoPeriodo");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdCurso", "IdPeriodo")
                        .IsUnique();

                    b.ToTable("CoursePeriods");
                });

            modelBuilder.Entity("Domain.Entities.CourseSubject", b =>
                {
                    b.Property<int>("IdCursoMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCursoMateria"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdCursoMateria");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdCurso", "IdMateria")
                        .IsUnique();

                    b.ToTable("CourseSubjects");
                });

            modelBuilder.Entity("Domain.Entities.Estudent", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("CodigoEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Estudents");
                });

            modelBuilder.Entity("Domain.Entities.Month", b =>
                {
                    b.Property<int>("IdMes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMes"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("IdMes");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Domain.Entities.Period", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeriodo"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPeriodo");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersona");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdProfesor");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("Domain.Entities.ProfessorSubject", b =>
                {
                    b.Property<int>("IdProfesorMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesorMateria"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdProfesorMateria");

                    b.HasIndex("IdMateria");

                    b.HasIndex("IdProfesor", "IdMateria")
                        .IsUnique();

                    b.ToTable("ProfessorSubjects");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Property<int>("IdSeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSeccion"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("CourseIdCurso")
                        .HasColumnType("int");

                    b.Property<int>("CupoCapacidadMaximo")
                        .HasColumnType("int");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSeccion");

                    b.HasIndex("CourseIdCurso");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("Domain.Entities.SessionPeriod", b =>
                {
                    b.Property<int>("IdSessionPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSessionPeriod"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdAula")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int");

                    b.Property<int>("IdSeccion")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdSessionPeriod");

                    b.HasIndex("IdAula");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdSeccion");

                    b.ToTable("SessionPeriod");
                });

            modelBuilder.Entity("Domain.Entities.SubPeriod", b =>
                {
                    b.Property<int>("IdSubPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubPeriodo"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdSubPeriodo");

                    b.ToTable("SubPeriods");
                });

            modelBuilder.Entity("Domain.Entities.Subject", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMateria");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Entities.TeachingAssignment", b =>
                {
                    b.Property<int>("IdAsignacionDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacionDocente"));

                    b.Property<string>("Activo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdProfesorMateria")
                        .HasColumnType("int");

                    b.Property<int>("IdSessionPeriod")
                        .HasColumnType("int");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdAsignacionDocente");

                    b.HasIndex("IdSessionPeriod");

                    b.HasIndex("IdProfesorMateria", "IdSessionPeriod")
                        .IsUnique();

                    b.ToTable("TeachingAssignment");
                });

            modelBuilder.Entity("Domain.Entities.AcademicMonth", b =>
                {
                    b.HasOne("Domain.Entities.Month", "Month")
                        .WithMany("AcademicMonths")
                        .HasForeignKey("IdMes")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AcademicSubPeriod", "AcademicSubPeriod")
                        .WithMany("AcademicMonths")
                        .HasForeignKey("IdPeriodoAcademico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicSubPeriod");

                    b.Navigation("Month");
                });

            modelBuilder.Entity("Domain.Entities.AcademicSubPeriod", b =>
                {
                    b.HasOne("Domain.Entities.Period", "Period")
                        .WithMany("AcademicSubPeriods")
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubPeriod", "SubPeriod")
                        .WithMany("AcademicSubPeriods")
                        .HasForeignKey("IdSubPeriodo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("SubPeriod");
                });

            modelBuilder.Entity("Domain.Entities.CDUser", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("Domain.Entities.CDUser", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Domain.Entities.CoursePeriod", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("CursoPeriodos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Period", "Period")
                        .WithMany("CoursePeriods")
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Domain.Entities.CourseSubject", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Subject", "Subject")
                        .WithMany("CourseSubjects")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Entities.Estudent", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Person")
                        .WithOne("Estudiante")
                        .HasForeignKey("Domain.Entities.Estudent", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.HasOne("Domain.Entities.Person", "Persona")
                        .WithOne("Profesor")
                        .HasForeignKey("Domain.Entities.Professor", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Domain.Entities.ProfessorSubject", b =>
                {
                    b.HasOne("Domain.Entities.Subject", "Subject")
                        .WithMany("ProfessorSubjects")
                        .HasForeignKey("IdMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Professor", "Professor")
                        .WithMany("ProfessorSubjects")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.HasOne("Domain.Entities.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseIdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entities.SessionPeriod", b =>
                {
                    b.HasOne("Domain.Entities.Classroom", "Classroom")
                        .WithMany("SessionPeriods")
                        .HasForeignKey("IdAula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Period", "Period")
                        .WithMany("SessionPeriods")
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Session", "Session")
                        .WithMany("SessionPeriods")
                        .HasForeignKey("IdSeccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Period");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Domain.Entities.TeachingAssignment", b =>
                {
                    b.HasOne("Domain.Entities.ProfessorSubject", "ProfessorSubject")
                        .WithMany()
                        .HasForeignKey("IdProfesorMateria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SessionPeriod", "SessionPeriod")
                        .WithMany()
                        .HasForeignKey("IdSessionPeriod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfessorSubject");

                    b.Navigation("SessionPeriod");
                });

            modelBuilder.Entity("Domain.Entities.AcademicSubPeriod", b =>
                {
                    b.Navigation("AcademicMonths");
                });

            modelBuilder.Entity("Domain.Entities.Classroom", b =>
                {
                    b.Navigation("SessionPeriods");
                });

            modelBuilder.Entity("Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseSubjects");

                    b.Navigation("CursoPeriodos");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Domain.Entities.Month", b =>
                {
                    b.Navigation("AcademicMonths");
                });

            modelBuilder.Entity("Domain.Entities.Period", b =>
                {
                    b.Navigation("AcademicSubPeriods");

                    b.Navigation("CoursePeriods");

                    b.Navigation("SessionPeriods");
                });

            modelBuilder.Entity("Domain.Entities.Person", b =>
                {
                    b.Navigation("Estudiante")
                        .IsRequired();

                    b.Navigation("Profesor")
                        .IsRequired();

                    b.Navigation("Usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorSubjects");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Session", b =>
                {
                    b.Navigation("SessionPeriods");
                });

            modelBuilder.Entity("Domain.Entities.SubPeriod", b =>
                {
                    b.Navigation("AcademicSubPeriods");
                });

            modelBuilder.Entity("Domain.Entities.Subject", b =>
                {
                    b.Navigation("CourseSubjects");

                    b.Navigation("ProfessorSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
